### ISSUE TITLE
how to setting the parity  field

### ISSUE THREAD

**Issue by pdn1993** [licheedev/Android-SerialPort-Tool#12]
Hello,i have tried your project (Android-SerialPort-Tool) , Everything is ok but  i don't know how to set the Parity  (EVEN) Field in your code

Thank you

**Comment by licheedev** [comment]
use the version 2.0.0
```
implementation 'com.github.licheedev:Android-SerialPort-API:2.0.0'
```

```java
// Default 8N1(8 databits、none parity、1 stopbits)
SerialPort serialPort = SerialPort.newBuilder(path, baudrate).build();

// 7E2(7 databits、even parity、2 stopbits)
SerialPort serialPort = SerialPort //
    .newBuilder(path, baudrate) 
    .parity(2) // parity；0:(NONE，default)；1:(ODD);2:(EVEN)
    .dataBits(7) // 5~8
    .stopBits(2) // 1~2, default 1
    .build();
```

**Comment by pdn1993** [comment]
i have used  version 2.0.0  and then  compiled but error 
com.android.dex.DexException: Multiple dex files define Landroid/serialport/SerialPort;

now i already have        multiDexEnabled true  in the build.gradle 

Do you have any solution? 

Thank you very much for your kindness

**Comment by licheedev** [comment]
@pdn1993 
remove this line first
[implementation 'com.github.licheedev.Android-SerialPort-API:serialport:1.0.1'](https://github.com/licheedev/Android-SerialPort-Tool/blob/5c89c81e0ba629bca1bcf7311f35d9f2d57fcfa5/app/build.gradle#L46)

**Comment by ped2019-dev** [comment]
Thank you very much , it works !
