### ISSUE TITLE
多对多串口

### ISSUE THREAD

**Issue by ShengjieGeng** [licheedev/Android-SerialPort-Tool#20]
请教一下，如果有个个需求，Android的多个串口读设备消息怎么实现呢？
我试过创建多个串口对象，打开不同的path，但是只能收到一个消息。

**Comment by a120476536** [comment]
不知道你是不是同时也开启了 多个线程读取。

**Comment by MagicZhang1-ctrl** [comment]
@ShengjieGeng 我也是出现了这个问题，尝试创建了多个串口对象，打开不同的path，但是一次只会有一个打开的串口正常通信，请问您最后是怎么解决这个问题的？

**Comment by ShengjieGeng** [comment]
> @ShengjieGeng 我也是出现了这个问题，尝试创建了多个串口对象，打开不同的path，但是一次只会有一个打开的串口正常通信，请问您最后是怎么解决这个问题的？

@master5277  我用了比较笨的方案，用了两个不同的串口库

**Comment by MagicZhang1-ctrl** [comment]
@ShengjieGeng 谢谢您的回复，我这边找到解决的方法了，感谢
