### ISSUE TITLE
How to read data using library

### ISSUE THREAD

**Issue by alirazaseptems** [licheedev/Android-SerialPort-Tool#8]
Hello, hope you are fine. I have used this library and it has helped me a lot to achieve my goals and I was able to connect and run commands on device. However my problem is that I also need to read data from the device. I have tried to read data by "inputStream.read(datas)" but my app stucks and dont return any data. Please help me. I ll be very grateful to you. thanks and regards.

    private Observable<Object> rxReadData(final byte[] datas) {

        return Observable.create(new ObservableOnSubscribe<Object>() {
            @Override
            public void subscribe(ObservableEmitter<Object> emitter) throws Exception {
                try {
                    int data = readData(datas);
                    emitter.onNext(new Object());
                } catch (Exception e) {

                    LogPlus.e("发送：" + ByteUtil.bytes2HexStr(datas) + " 失败", e);

                    if (!emitter.isDisposed()) {
                        emitter.onError(e);
                        return;
                    }
                }
                emitter.onComplete();
            }
        });
    }

 private int readData(byte[] datas) throws Exception {
        return inputStream.read(datas);
    }

**Comment by licheedev** [comment]
@alirazaseptems Don't read data like this, it will never return or be interrupted until the `inputStream` reads some bytes.

I wrote another repo, hope it can help you. But Sorry for my poor English, all the comments are in Chinese.
> https://github.com/licheedev/SerialWorker

Just impletement Your Own SerialWorker like this [DoorSerialWorker.java](https://github.com/licheedev/SerialWorker/blob/master/app/src/main/java/com/licheedev/serialworkerdemo/serial/DoorSerialWorker.java)

**Comment by alirazaseptems** [comment]
thank you so much. @licheedev

**Comment by alirazaseptems** [comment]
One more thing. I was getting all the device and It was working fine. I just start getting empty array in "serialPortFinder.getAllDevicesPath();". I dont know how it happened. Can you tell me what are the possible causes of this. It was working fine earlier and stopped working now. @licheedev

**Comment by alirazaseptems** [comment]
java.io.FileNotFoundException: /proc/tty/drivers (Permission denied) 
I get this exception. I also have given the storage permission.

**Comment by licheedev** [comment]
I have never encountered this problem. Do you install your application on the same device before and after? Try `adb shell` to check the permission of `/proc/tty/drivers`.

**Comment by alirazaseptems** [comment]
yes, its the same device. and here are the permissions

    install permissions:
      com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE: granted=true
      com.google.android.c2dm.permission.RECEIVE: granted=true
      android.permission.INTERNET: granted=true
      android.permission.ACCESS_NETWORK_STATE: granted=true
      android.permission.WAKE_LOCK: granted=true
    User 0: ceDataInode=-4294917718 installed=true hidden=false suspended=false stopped=false notLaunched=false enabled=0 instant=false virtual=false
    overlay paths:
      /vendor/overlay/framework-res__auto_generated_rro.apk
      gids=[3003]
      runtime permissions:
        android.permission.READ_EXTERNAL_STORAGE: granted=true
        android.permission.WRITE_EXTERNAL_STORAGE: granted=true

**Comment by alirazaseptems** [comment]
@licheedev .. I have found the issue. I updated my support libraries to 28 and it caused the issue. now I reverted back to 27 and it is working now. Can you see the issue by updating support libraries and look why it is happening on new versions?
ext {
    compileSdkVersion = 28

    minSdkVersion = 18
    targetSdkVersion = 28

    supportVersion = "28.0.0"
}
